//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by usbcap.rc
//
#define ID_EXIT                         40001
#define ID_START                        40002
#define ID_FORMAT_DLG                   40003
#define ID_DISPLAY_DLG                  40004
#define ID_COMPRESSION_DLG              40005
#define ID_SOURCE_DLG                   40006
#define ID_AUDIOFORMAT_DLG              40009
#define ID_PREVIEW                      40011
#define ID_SINGLE_FRAME                 40013
#define ID_CAPTUREFILE                  40014
#define ID_SAVEAS                       40015
#define ID_SAVEDIB                      40016
#define ID_CLIPBOARD                    40017

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40018
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
